version: "3"
services:
  consul-server-1:
    image: consul:1.0.3
    entrypoint:
      - consul
      - agent
      - -server
      - -ui
      - -data-dir=/tmp/consul
      - -bootstrap-expect=3
  consul-server-2:
    image: consul:1.0.3
    entrypoint:
      - consul
      - agent
      - -server
      - -data-dir=/tmp/consul
      - -bootstrap-expect=3
      - -retry-join
      - "consul-server-1"
  consul-server-3:
    image: consul:1.0.3
    entrypoint:
      - consul
      - agent
      - -server
      - -data-dir=/tmp/consul
      - -bootstrap-expect=3
      - -retry-join
      - "consul-server-1"
  consul-ui:
    image: consul:1.0.3
    entrypoint:
      - consul
      - agent
      - -ui
      - -data-dir=/tmp/consul
      - -retry-join
      - "consul-server-1"
    ports:
      - "8300:8300"
      - "8301:8301"
      - "8302:8302"
      - "8500:8500"
      - "8600:8600"
