FROM consul:1.0.3

USER root

RUN apk update \
  && apk add mongodb

WORKDIR /

ADD ./healthchecks healthchecks/

RUN chmod +x /healthchecks/mongodb.sh

ENTRYPOINT [ \
  "consul", \
  "agent", \
  "-config-dir=/etc/consul.d", \
  "-enable-script-checks", \
  "-data-dir=/tmp/consul", \
  "-retry-join", \
  "consul-server-1" \
]
