version: "3"
services:
  mongo-node-1:
    image: mongo:3.7-jessie
  consul-agent-1:
    build:
      dockerfile: ./Dockerfile.consul_agent
      context: .
  koa-web:
    build:
      dockerfile: ./Dockerfile.koa
      context: '.'
