FROM consul:1.0.3

RUN apk update \
  && apk add mongodb openrc

RUN mkdir -p /data/db

WORKDIR /

COPY ./etc/init.d/consul etc/init.d/consul
COPY ./etc/consul.d/mongodb.hcl /etc/consul.d/mongodb.hcl

ADD ./healthchecks healthchecks/

RUN chmod +x /healthchecks/mongodb.sh
RUN chmod +x /etc/init.d/consul
RUN rc-update add consul default

ENTRYPOINT rc-service consul status & mongod
