FROM consul:1.0.3

USER root

ADD . ./

RUN apk update && \
  apk add nodejs yarn openrc && \
  yarn install

COPY ./etc/consul.d/web.hcl /etc/consul.d/web.hcl
COPY ./etc/init.d/consul /etc/init.d/consul

RUN chmod +x /etc/init.d/consul
RUN rc-update add consul default

ENTRYPOINT rc-service consul status & node app.js
